# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'office_keywords_replace.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1007, 842)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 60, 60, 16))
        self.label.setObjectName("label")
        self.start_transfer = QtWidgets.QPushButton(self.centralwidget)
        self.start_transfer.setGeometry(QtCore.QRect(200, 280, 521, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.start_transfer.setFont(font)
        self.start_transfer.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.start_transfer.setObjectName("start_transfer")
        self.ori_dir = QtWidgets.QLineEdit(self.centralwidget)
        self.ori_dir.setGeometry(QtCore.QRect(230, 60, 381, 21))
        self.ori_dir.setObjectName("ori_dir")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 90, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 160, 45, 16))
        self.label_3.setObjectName("label_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(200, 350, 521, 211))
        self.textBrowser.setObjectName("textBrowser")
        self.transfer_dir = QtWidgets.QLineEdit(self.centralwidget)
        self.transfer_dir.setGeometry(QtCore.QRect(230, 90, 381, 21))
        self.transfer_dir.setObjectName("transfer_dir")
        self.choose_ori_dir = QtWidgets.QPushButton(self.centralwidget)
        self.choose_ori_dir.setGeometry(QtCore.QRect(630, 60, 93, 28))
        self.choose_ori_dir.setObjectName("choose_ori_dir")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(630, 90, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(220, 130, 421, 121))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1007, 26))
        self.menubar.setObjectName("menubar")
        self.menude = QtWidgets.QMenu(self.menubar)
        self.menude.setObjectName("menude")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menude.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "目录位置"))
        self.start_transfer.setText(_translate("MainWindow", "开始转换"))
        self.label_2.setText(_translate("MainWindow", "目录位置"))
        self.label_3.setText(_translate("MainWindow", "替换词"))
        self.choose_ori_dir.setText(_translate("MainWindow", "选择目录"))
        self.pushButton.setText(_translate("MainWindow", "存储位置"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.menude.setTitle(_translate("MainWindow", "证优客咨询师文档转换工具V1.0"))
