# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqt5_office_keywords_replace_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1007, 842)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(870, 250, 121, 21))
        self.label_4.setObjectName("label_4")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(50, 20, 781, 751))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.ori_dir = QtWidgets.QLabel(self.widget)
        self.ori_dir.setWordWrap(False)
        self.ori_dir.setObjectName("ori_dir")
        self.gridLayout.addWidget(self.ori_dir, 0, 0, 1, 1)
        self.ori_dir_input = QtWidgets.QLineEdit(self.widget)
        self.ori_dir_input.setObjectName("ori_dir_input")
        self.gridLayout.addWidget(self.ori_dir_input, 0, 1, 1, 1)
        self.ori_dir_btn = QtWidgets.QPushButton(self.widget)
        self.ori_dir_btn.setObjectName("ori_dir_btn")
        self.gridLayout.addWidget(self.ori_dir_btn, 0, 2, 1, 1)
        self.replace_dir = QtWidgets.QLabel(self.widget)
        self.replace_dir.setObjectName("replace_dir")
        self.gridLayout.addWidget(self.replace_dir, 1, 0, 1, 1)
        self.replace_dir_input = QtWidgets.QLineEdit(self.widget)
        self.replace_dir_input.setObjectName("replace_dir_input")
        self.gridLayout.addWidget(self.replace_dir_input, 1, 1, 1, 1)
        self.replace_dir_btn = QtWidgets.QPushButton(self.widget)
        self.replace_dir_btn.setObjectName("replace_dir_btn")
        self.gridLayout.addWidget(self.replace_dir_btn, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.replace_words = QtWidgets.QTextEdit(self.widget)
        self.replace_words.setObjectName("replace_words")
        self.horizontalLayout.addWidget(self.replace_words)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.start_transfer = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.start_transfer.setFont(font)
        self.start_transfer.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.start_transfer.setObjectName("start_transfer")
        self.verticalLayout.addWidget(self.start_transfer)
        self.result_display = QtWidgets.QTextBrowser(self.widget)
        self.result_display.setObjectName("result_display")
        self.verticalLayout.addWidget(self.result_display)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1007, 26))
        self.menubar.setObjectName("menubar")
        self.menude = QtWidgets.QMenu(self.menubar)
        self.menude.setObjectName("menude")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menude.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "关键词一行一个"))
        self.ori_dir.setText(_translate("MainWindow", "替换目录"))
        self.ori_dir_btn.setText(_translate("MainWindow", "选择目录"))
        self.replace_dir.setText(_translate("MainWindow", "目录位置"))
        self.replace_dir_btn.setText(_translate("MainWindow", "存储位置"))
        self.label_3.setText(_translate("MainWindow", "替换词"))
        self.replace_words.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.start_transfer.setText(_translate("MainWindow", "开始转换"))
        self.menude.setTitle(_translate("MainWindow", "证优客咨询师文档转换工具V1.0"))
